Questions:
  - key: source
    type: select
    label: "Select the problem source"
    data:
      options:
        - value: leetcode
        - value: others
    subquestion_condition: leetcode
    subquestions:
      - key: ProblemName
        type: text
        label: "What problem did you solve?"
        data:
          min: 0
          max: -1

TemplateCommit: |
  [<source>] Added '<ProblemName>' solution
  
Colors:
  primary: "6"
  secondary: "2"
  green: "2"
  red: "1"
